version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: kaggle_postgres
    restart: always
    environment:
      POSTGRES_USER: kaggle_user
      POSTGRES_PASSWORD: kaggle_password
      POSTGRES_DB: kaggle_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
